export const MOCK_POSTS = [
  {
    id: '1',
    content: 'The new hire at my company walked out of their first standup after exactly 4 minutes and never came back. No resignation email. No Slack message. Just... gone. HR is losing their minds 💀',
    media_url: null,
    is_anonymous: false,
    category: 'Work',
    temp_score: 94,
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    likes_count: 247,
    comments_count: 43,
    user: {
      id: 'u1',
      username: 'spilltea_stacy',
      display_name: 'Stacy M.',
      avatar_url: null,
    },
    liked_by_me: false,
  },
  {
    id: '2',
    content: 'hot take: that startup everyone hyped last month is running on fumes and the "Series A closed" announcement was literally dad\'s money laundered through an LLC. i have receipts but i value my life 🫖',
    media_url: null,
    is_anonymous: true,
    category: 'Tech',
    temp_score: 78,
    created_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    likes_count: 89,
    comments_count: 17,
    user: null,
    liked_by_me: true,
  },
  {
    id: '3',
    content: 'unpopular but i will die on this hill: every "girl math" girlboss manifesting arc is just privilege + luck wearing a vision board costume. change my mind.',
    media_url: null,
    is_anonymous: false,
    category: 'Culture',
    temp_score: 41,
    created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    likes_count: 31,
    comments_count: 8,
    user: {
      id: 'u3',
      username: 'real_xoanna',
      display_name: 'Xoanna R.',
      avatar_url: null,
    },
    liked_by_me: false,
  },
  {
    id: '4',
    content: 'my professor just accidentally screen shared his tinder while presenting the quarterly stats deck to 200 students. the profile name. the bio. i will never recover from what i witnessed.',
    media_url: null,
    is_anonymous: false,
    category: 'School',
    temp_score: 99,
    created_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    likes_count: 1204,
    comments_count: 331,
    user: {
      id: 'u4',
      username: 'campus_chronicles',
      display_name: 'Campus Chron.',
      avatar_url: null,
    },
    liked_by_me: false,
  },
  {
    id: '5',
    content: 'the way my entire team pretended not to notice the CEO mispronouncing "synergy" as "sin-ergy" in every single all-hands for THREE YEARS until someone finally put it in the anonymous feedback form',
    media_url: null,
    is_anonymous: true,
    category: 'Work',
    temp_score: 22,
    created_at: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
    likes_count: 14,
    comments_count: 3,
    user: null,
    liked_by_me: false,
  },
]
